site_name: Epsilon
site_description: Documentation for Epsilon
repo_url: https://github.com/YOUR_USERNAME/Epsilon
repo_name: github.com/JakubLiu/Epsilon


theme:
  name: material


  features:
    - content.code.copy

  palette:

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: index.md

  - Installation: installation.md

  - Usage:

      - Overview: usage/index.md

      - Config file structure:
        - reference_genome: usage/config_struct/reference_genome.md
        - negative_control_bamlist: usage/config_struct/negative_control_bamlist.md
        - loci_list: usage/config_struct/loci_list.md
        - alt_mode: usage/config_struct/alt_mode.md
        - nranks: usage/config_struct/nranks.md
        - max_noise_level: usage/config_struct/max_noise_level.md
        - tumor_path: usage/config_struct/tumor_path.md
        - matched_normal_path: usage/config_struct/matched_normal_path.md
        - calling_loci_list: usage/config_struct/calling_loci_list.md
        - variant_calling_model: usage/config_struct/variant_calling_model.md
        - fdr_method: usage/config_struct/fdr_method.md
        - alpha: usage/config_struct/alpha.md
        - prior: usage/config_struct/prior.md
        - posterior_cutoff: usage/config_struct/posterior_cutoff.md
        - output_vcf: usage/config_struct/output_vcf.md

      - Output: usage/output.md


  - Examples: examples.md

  - Advanced usage:
    - Using an already fitted error model: advanced_usage/epsilon_call.md
    - Epsilon and Slurm: advanced_usage/slurm.md